services:
  psicosaas:
    build:
      context: .
      args:
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
        - NEXT_PUBLIC_STRIPE_PUBLIC_KEY=${NEXT_PUBLIC_STRIPE_PUBLIC_KEY}
    container_name: psicosaas
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - WHATS_API_KEY=${WHATS_API_KEY}
      - WHATS_MASTER_INSTANCE=${WHATS_MASTER_INSTANCE}
      - NODE_OPTIONS=--dns-result-order=ipv4first
    depends_on:
      - psicosaas_db

  psicosaas_db:
    image: postgres:15-alpine
    container_name: psicosaas_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=intelbras3246
      - POSTGRES_DB=psico_db
    ports:
      - "5432:5432"
    volumes:
      - psicosaas_db_data:/var/lib/postgresql/data

  wppconnect:
    image: wppconnect/server-cli:latest
    container_name: wppconnect
    restart: always
    ports:
      - "21465:21465"
    command: ["--secretKey", "${WHATS_API_KEY:-123456}", "--port", "21465", "--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage"]
    environment:
      - PORT=21465
      - SECRET_KEY=${WHATS_API_KEY:-"123456"}
      - AUTHENTICATION_SECRET_KEY=${WHATS_API_KEY:-"123456"}
      - WEBHOOK_URL=${NEXT_PUBLIC_APP_URL}/api/whatsapp/webhook

volumes:
  psicosaas_db_data:

networks:
  default:
    name: public_network
    external: true

