services:
  psicosaas:
    build:
      context: .
      args:
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
        - NEXT_PUBLIC_STRIPE_PUBLIC_KEY=${NEXT_PUBLIC_STRIPE_PUBLIC_KEY}
    container_name: psicosaas
    restart: always
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:intelbras3246@psicosaas_db:5432/psico_db
      - DIRECT_URL=postgresql://postgres:intelbras3246@psicosaas_db:5432/psico_db
      - JWT_SECRET=${JWT_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - WHATS_API_URL=http://evolution:8080
      - WHATS_API_KEY=${WHATS_API_KEY:-"123456"}
      - NODE_OPTIONS=--dns-result-order=ipv4first
    depends_on:
      - psicosaas_db
      - evolution
    networks:
      - psico_net

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=www.laisbritoofc.com.br
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - psicosaas
    networks:
      - psico_net

  psicosaas_db:
    image: postgres:15-alpine
    container_name: psicosaas_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=intelbras3246
      - POSTGRES_DB=psico_db
    ports:
      - "5432:5432"
    volumes:
      - psicosaas_db_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - psico_net

  evolution:
    image: atendai/evolution-api:v1.8.2
    container_name: evolution
    restart: always
    environment:
      - SERVER_TYPE=express
      - PORT=8080
      - SERVER_PORT=8080
      - DOCKER_ENV=true
      - AUTH_TOKEN=${WHATS_API_KEY:-"123456"}
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=${WHATS_API_KEY:-"123456"}
      - DATABASE_ENABLED=false
      - LOG_LEVEL=DEBUG
      - LOG_COLOR=true
      - DEL_INSTANCE=false
    ports:
      - "8080:8080"
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - psico_net
    depends_on:
      - psicosaas_db

volumes:
  psicosaas_db_data:
  evolution_instances:
  caddy_data:
  caddy_config:

networks:
  psico_net:
    driver: bridge
